title: "abizi.xyz"
remote_theme: pmarsceill/just-the-docs

# Theme settings
# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/taruma/hidrokit-nb"